---
- hosts: falcon
  tasks:
    - include_tasks: tasks/dependencies.yml
    - include_tasks: tasks/init.yml
    - include_tasks: tasks/pip-installation.yml
    - include_tasks: tasks/server-hardening.yml
    - include_tasks: tasks/database-setup.yml
    - include_tasks: tasks/rails-setup.yml
    - include_tasks: tasks/docker-setup.yml
    - include_tasks: tasks/nginx-setup.yml
