---
- name: Create /CORE directory
  file:
    path: /CORE
    state: directory
    owner: vagrant
    mode: 0775

- name: Git clone
  become: yes
  become_user: vagrant
  git:
    repo: 'https://github.com/UnifiedPaymentSolutions/rails_sample.git'
    dest: /CORE/rails_sample