---
- name: "Update and upgrade apt packages"
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 # One day cache

- name: "Install Dependencies"
  apt:
    state: latest
    update_cache: yes
    pkg:
    - python
    - htop
    - ntp
    - vim
    - curl
    - ufw
    - ruby
    - build-essential
    - ruby-dev
    - zlib1g-dev
    - libpq-dev
    - sudo
    - postgresql
    - python-psycopg2
    - ruby-bundler
    - git
    - fail2ban
