---
- name: "Install Dependencies"
  apt:
    state: latest
    update_cache: yes
    pkg:
    - python
    - ntp
    - vim
    - wget
    - curl
    - screen
    - htop
    - smartmontools
    - sudo
