---
- name: "Update and upgrade apt packages"
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: "Install Dependencies"
  apt:
    state: latest
    update_cache: yes
    pkg:
    - python
    - ntp
    - vim
    - wget
    - curl
    - screen
    - htop
    - smartmontools
    - sudo
    - ufw
    - apt-transport-https

- name: "Add TCP Rules to firewall"
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
    - 443
    - 80
    - 22

- name: "Enable Firewall"
  systemd:
    name: ufw
    state: started
    enabled: yes
    masked: no
    daemon_reload: yes

- name: "Enable UFW"
  ufw:
    state: enabled

- name: "Enable NTP"
  systemd:
    name: ntp
    state: started
    enabled: yes
    masked: no
    daemon_reload: yes

- name: "set timezone to Asia/Tehran"
  timezone:
    name: Asia/Tehran
