---
- name: Create NGINX conf.d directories
  file:
    path: /CORE/local-nginx/nginx/conf.d
    state: directory
    owner: root
    group: root
    mode: 0775

- name: Create NGINX certs directories
  file:
    path: /CORE/local-nginx/nginx/certs
    state: directory
    owner: root
    group: root
    mode: 0775

- name: Run NGINX in Docker
  docker_container:
    name: local_nginx
    image: nginx:stable-alpine
    network_mode: host
    restart_policy: always
    volumes:
      - /CORE/local-nginx/nginx/conf.d:/etc/nginx/conf.d:ro
      - /CORE/local-nginx/nginx/certs:/etc/nginx/certs:ro

