---
- name: Create NGINX conf.d directories
  file:
    path: /CORE/local-nginx/nginx/conf.d
    state: directory
    owner: root
    group: root
    mode: 0775

- name: Create NGINX certs directories
  file:
    path: /CORE/local-nginx/nginx/certs
    state: directory
    owner: root
    group: root
    mode: 0775

- name: Copy NGINX config file
  copy:
    remote_src: no
    src: \"{{ local_pwd_ansible_path }}\"/files/nginx-host.conf
    dest: /CORE/local-nginx/nginx/conf.d/{{ domain_fqdn_address }}.conf
    owner: root
    group: root
    mode: 0644
    force: yes
    template:
      src: code.conf.j2

- name: Generate an OpenSSL private key.
  openssl_privatekey:
    path: /CORE/local-nginx/nginx/certs/{{ domain_fqdn_address }}.pem
    size: 2048

- name: Generate an OpenSSL CSR.
  openssl_csr:
    path: /CORE/local-nginx/nginx/certs/{{ domain_fqdn_address }}.csr
    privatekey_path: /CORE/local-nginx/nginx/certs/{{ domain_fqdn_address }}.pem
    common_name: "{{ domain_fqdn_address }}"
    digest: 'sha256'
    country_name: 'IR'
    state_or_province_name: 'Tehran'
    locality_name: 'Tehran'
    organization_name: 'Falcon Co'
    organizational_unit_name: 'IT Team'
    email_address: 'support@{{ domain_fqdn_address }}'
    subject_alt_name: 'DNS: www.{{ domain_fqdn_address }}'

- name: Generate a Self Signed OpenSSL certificate.
  openssl_certificate:
    path: /CORE/local-nginx/nginx/certs/{{ domain_fqdn_address }}-fullchain.pem
    privatekey_path: /CORE/local-nginx/nginx/certs/{{ domain_fqdn_address }}.pem
    csr_path: /CORE/local-nginx/nginx/certs/{{ domain_fqdn_address }}.csr
    provider: selfsigned

- name: Generate a Diffie-Hellman key.
  openssl_dhparam:
    path: /CORE/local-nginx/nginx/certs/dhparams.pem
    size: 2048

- name: Run NGINX in Docker
  docker_container:
    name: local_nginx
    image: nginx:stable-alpine
    network_mode: host
    restart_policy: always
    output_logs: yes
    log_driver: json-file
    log_options:
      max-size: 10m
      max-file: 5
    volumes:
      - /CORE/local-nginx/nginx/conf.d:/etc/nginx/conf.d:ro
      - /CORE/local-nginx/nginx/certs:/etc/nginx/certs:ro
